name: Build and Push Images to GCP
on:
  push:
    branches: ['main']

jobs:
  build-push-gcr:
    name: Build and push to GCR
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: hello-app
      PROJECT_ID: tuk-scit-project1

    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          python-version: ${{ matrix.python_version }}
          
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credential: true

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .
      
      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Push Docker Image to Google Container Registry (GCR)
        env:
          GIT_TAG: v0.1.0
          IMAGE_REPO: hello-app-python
        run: |-
          docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$PROJECT_ID/$IMAGE_REPO/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$PROJECT_ID/$IMAGE_REPO/$IMAGE_NAME:$GIT_TAG
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/$IMAGE_REPO/$IMAGE_NAME:latest
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/$IMAGE_REPO/$IMAGE_NAME:$GIT_TAG